// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using edumis.DataAccess;

#nullable disable

namespace edumis.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250106092629_Resolution_SMC_Model_Changes")]
    partial class Resolution_SMC_Model_Changes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("edumis.Models.Circulars.CircularModel", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CircularDate")
                        .HasColumnType("date")
                        .HasColumnName("circulardate");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FileLink")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("filelink");

                    b.Property<string>("FinancialYear")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("financialyear");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("isvalid");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("WebLink")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("weblink");

                    b.HasKey("RowId");

                    b.ToTable("tbweb_circulars");
                });

            modelBuilder.Entity("edumis.Models.Communication.OTPSentModel", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("IPAddress")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("ipaddress");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("otp");

                    b.Property<string>("Purpose")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("purpose");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sentdate");

                    b.Property<string>("SentTo")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sentto");

                    b.Property<DateTime>("ValidUpTo")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("validupto");

                    b.HasKey("RowId");

                    b.ToTable("tbcom_sentotp");
                });

            modelBuilder.Entity("edumis.Models.Communication.SMSSettingsModel", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.Property<string>("AppKey")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("appkey");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("isvalid");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("password");

                    b.Property<string>("SMSURL")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("smsurl");

                    b.Property<string>("SecureKey")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("securekey");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("senderid");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("userid");

                    b.HasKey("RowId");

                    b.ToTable("tbcom_sms_settings");
                });

            modelBuilder.Entity("edumis.Models.Communication.SMSTemplatesModel", b =>
                {
                    b.Property<string>("TemplateId")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("templateid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("isvalid");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.Property<int>("SMSType")
                        .HasColumnType("integer")
                        .HasColumnName("smstype");

                    b.HasKey("TemplateId");

                    b.ToTable("tbcom_smstemplates");
                });

            modelBuilder.Entity("edumis.Models.Employees.AppointmentModel", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("employeeid");

                    b.Property<DateTime?>("AppointmentDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("appointmentdate");

                    b.Property<string>("AppointmentOrder")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("appointmentorder");

                    b.Property<int>("AppointmentType")
                        .HasColumnType("integer")
                        .HasColumnName("appointmenttype");

                    b.Property<DateTime>("BranchJoiningDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("branchjoiningdate");

                    b.Property<int>("Cadre")
                        .HasColumnType("integer")
                        .HasColumnName("cadre");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("CurrentBranch")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("currentbranch");

                    b.Property<int>("CurrentPostHeld")
                        .HasColumnType("integer")
                        .HasColumnName("currentpostheld");

                    b.Property<string>("CurrentScale")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("currentscale");

                    b.Property<int>("Designation")
                        .HasColumnType("integer")
                        .HasColumnName("designation");

                    b.Property<string>("Grade")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("grade");

                    b.Property<DateTime?>("GradeGrantDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("gradegrantdate");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<int>("RecruitmentType")
                        .HasColumnType("integer")
                        .HasColumnName("recruitmenttype");

                    b.Property<DateTime?>("RetirementDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("retirementdate");

                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.Property<int?>("SeniorityNo")
                        .HasColumnType("integer")
                        .HasColumnName("seniorityno");

                    b.HasKey("EmployeeId");

                    b.ToTable("tbmsempappointmentdetails");
                });

            modelBuilder.Entity("edumis.Models.Employees.EducationModel", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("employeeid");

                    b.Property<int>("SerialNo")
                        .HasColumnType("integer")
                        .HasColumnName("serialno");

                    b.Property<string>("Board")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("board");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("Grade")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("grade");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("issuedate");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("numeric")
                        .HasColumnName("percentage");

                    b.Property<int>("Qualification")
                        .HasColumnType("integer")
                        .HasColumnName("qualification");

                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.Property<string>("Subjects")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("subjects");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.HasKey("EmployeeId", "SerialNo");

                    b.ToTable("tbmsempeducationdetails");
                });

            modelBuilder.Entity("edumis.Models.Employees.EmployeeModel", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("employeeid");

                    b.Property<string>("AadharNo")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("aadharno");

                    b.Property<string>("CCity")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ccity");

                    b.Property<string>("CPincode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("cpincode");

                    b.Property<int?>("CState")
                        .HasColumnType("integer")
                        .HasColumnName("cstate");

                    b.Property<int?>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("CorrespondenceAddress")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("correspondenceaddress");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dob");

                    b.Property<int?>("DisabilityType")
                        .HasColumnType("integer")
                        .HasColumnName("disabilitytype");

                    b.Property<string>("EmailId")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("emailid");

                    b.Property<string>("FatherName")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("fathername");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("firstname");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<int?>("HighestQualification")
                        .HasColumnType("integer")
                        .HasColumnName("highestqualification");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool?>("IsAnyDisability")
                        .HasColumnType("boolean")
                        .HasColumnName("isanydisability");

                    b.Property<bool?>("IsGazetted")
                        .HasColumnType("boolean")
                        .HasColumnName("isgazetted");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("lastname");

                    b.Property<int?>("MaritalStatus")
                        .HasColumnType("integer")
                        .HasColumnName("maritalstatus");

                    b.Property<string>("MiddleName")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("middlename");

                    b.Property<string>("MobileNo")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("mobileno");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<string>("MotherName")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("mothername");

                    b.Property<string>("OtherDisabilityType")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("otherdisabilitytype");

                    b.Property<string>("PCity")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("pcity");

                    b.Property<string>("PPincode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ppincode");

                    b.Property<int?>("PState")
                        .HasColumnType("integer")
                        .HasColumnName("pstate");

                    b.Property<string>("PanNo")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("panno");

                    b.Property<string>("PermanentAddress")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("permanentaddress");

                    b.Property<string>("Remarks")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remarks");

                    b.Property<string>("ReportingPersonId")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("reportingpersonid");

                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.Property<int?>("SelectionCategory")
                        .HasColumnType("integer")
                        .HasColumnName("selectioncategory");

                    b.Property<int?>("SubCategory")
                        .HasColumnType("integer")
                        .HasColumnName("subcategory");

                    b.Property<bool?>("VehicleFacilityAvailed")
                        .HasColumnType("boolean")
                        .HasColumnName("vehiclefacilityavailed");

                    b.HasKey("EmployeeId");

                    b.ToTable("tbmsemployees");
                });

            modelBuilder.Entity("edumis.Models.Global.CodeValuesModel", b =>
                {
                    b.Property<int>("CodeValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("codevalue");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodeValue"));

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<string>("CodeValDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("codevaldescription");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<int?>("ParentCode")
                        .HasColumnType("integer")
                        .HasColumnName("parentcode");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.HasKey("CodeValue");

                    b.HasIndex("Code");

                    b.ToTable("tbglcodevalues");
                });

            modelBuilder.Entity("edumis.Models.Global.CodesModel", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<string>("CodeDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("codedescription");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.HasKey("Code");

                    b.ToTable("tbglcodes");
                });

            modelBuilder.Entity("edumis.Models.Global.DesignationMenuItems", b =>
                {
                    b.Property<int>("DesignationId")
                        .HasColumnType("integer")
                        .HasColumnName("designationid");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("menuid");

                    b.Property<bool?>("CanCreate")
                        .HasColumnType("boolean")
                        .HasColumnName("cancreate");

                    b.Property<bool?>("CanDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("candelete");

                    b.Property<bool?>("CanEdit")
                        .HasColumnType("boolean")
                        .HasColumnName("canedit");

                    b.Property<bool?>("CanView")
                        .HasColumnType("boolean")
                        .HasColumnName("canview");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.HasKey("DesignationId", "MenuId");

                    b.ToTable("tbgldesignationmenuitems");
                });

            modelBuilder.Entity("edumis.Models.Global.DesignationUserTypeMapping", b =>
                {
                    b.Property<int>("DesignationId")
                        .HasColumnType("integer")
                        .HasColumnName("designationid");

                    b.Property<int>("UserType")
                        .HasColumnType("integer")
                        .HasColumnName("usertype");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.HasKey("DesignationId", "UserType");

                    b.ToTable("tbglmapdesigwithusertype");
                });

            modelBuilder.Entity("edumis.Models.Global.ExceptionLogs", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("errormessage");

                    b.Property<string>("InnerMessage")
                        .IsRequired()
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("innermessage");

                    b.Property<string>("Origin")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("origin");

                    b.Property<string>("StackTrace")
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("stacktrace");

                    b.HasKey("RowId");

                    b.ToTable("tbglexceptionlogs");
                });

            modelBuilder.Entity("edumis.Models.Global.Menus", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("menuid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MenuId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("isvalid");

                    b.Property<string>("MenuTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("menutitle");

                    b.Property<string>("Menuurl")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("menuurl");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<int?>("Module")
                        .HasColumnType("integer")
                        .HasColumnName("module");

                    b.Property<int?>("ParentMenuId")
                        .HasColumnType("integer")
                        .HasColumnName("parentmenuid");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.HasKey("MenuId");

                    b.ToTable("tbglmenus");
                });

            modelBuilder.Entity("edumis.Models.Global.SessionInfoModel", b =>
                {
                    b.Property<string>("ForSession")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("forsession");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("iscurrent");

                    b.Property<bool>("IsRegistrationOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("isregistrationopen");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("isvalid");

                    b.Property<DateOnly?>("LateRegistrationEndDate")
                        .HasColumnType("date")
                        .HasColumnName("lateregistrationenddate");

                    b.Property<TimeOnly?>("LateRegistrationEndTime")
                        .HasColumnType("time")
                        .HasColumnName("lateregistrationendtime");

                    b.Property<DateOnly?>("LateRegistrationStartDate")
                        .HasColumnType("date")
                        .HasColumnName("lateregistrationstartdate");

                    b.Property<TimeOnly?>("LateRegistrationStartTime")
                        .HasColumnType("time")
                        .HasColumnName("lateregistrationstarttime");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<DateOnly?>("Reg_AgeAsOnDate")
                        .HasColumnType("date")
                        .HasColumnName("reg_ageasondate");

                    b.Property<DateOnly?>("RegistrationEndDate")
                        .HasColumnType("date")
                        .HasColumnName("registrationenddate");

                    b.Property<TimeOnly?>("RegistrationEndTime")
                        .HasColumnType("time")
                        .HasColumnName("registrationendtime");

                    b.Property<DateOnly?>("RegistrationStartDate")
                        .HasColumnType("date")
                        .HasColumnName("registrationstartdate");

                    b.Property<TimeOnly?>("RegistrationStartTime")
                        .HasColumnType("time")
                        .HasColumnName("registrationstarttime");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.HasKey("ForSession");

                    b.ToTable("tbglacademicsessions");
                });

            modelBuilder.Entity("edumis.Models.Masters.BranchesModel", b =>
                {
                    b.Property<string>("BranchId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("branchid");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("branchname");

                    b.Property<int>("BranchType")
                        .HasColumnType("integer")
                        .HasColumnName("branchtype");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("buildingid");

                    b.Property<string>("ContactNo")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contactno");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("DistrictId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("districtid");

                    b.Property<string>("EmailId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("emailid");

                    b.Property<string>("InchargeId")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("inchargeid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<string>("ParentBranchId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("parentbranchid");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.Property<string>("ZoneId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("zoneid");

                    b.HasKey("BranchId");

                    b.ToTable("tbmsbranches");
                });

            modelBuilder.Entity("edumis.Models.Masters.DesignationModel", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<int>("DesignationGroup")
                        .HasColumnType("integer")
                        .HasColumnName("designationgroup");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool>("IsGazetted")
                        .HasColumnType("boolean")
                        .HasColumnName("isgazetted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.HasKey("RowId");

                    b.ToTable("tbmsdesignations");
                });

            modelBuilder.Entity("edumis.Models.Masters.DistrictsModel", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.HasKey("RowId");

                    b.ToTable("tbms_districts");
                });

            modelBuilder.Entity("edumis.Models.Masters.InfrastructureModel", b =>
                {
                    b.Property<string>("BuildingId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("buildingid");

                    b.Property<bool?>("Accommodation")
                        .HasColumnType("boolean")
                        .HasColumnName("accommodation");

                    b.Property<bool?>("ArcheryGround")
                        .HasColumnType("boolean")
                        .HasColumnName("archeryground");

                    b.Property<bool?>("BadmintonCourt")
                        .HasColumnType("boolean")
                        .HasColumnName("badmintoncourt");

                    b.Property<bool?>("BasketBallCourt")
                        .HasColumnType("boolean")
                        .HasColumnName("basketballcourt");

                    b.Property<bool?>("BoxingArena")
                        .HasColumnType("boolean")
                        .HasColumnName("boxingarena");

                    b.Property<string>("BuildingName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("buildingname");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<bool?>("CycleStand")
                        .HasColumnType("boolean")
                        .HasColumnName("cyclestand");

                    b.Property<bool?>("DrinkingWater")
                        .HasColumnType("boolean")
                        .HasColumnName("drinkingwater");

                    b.Property<bool?>("Fencing")
                        .HasColumnType("boolean")
                        .HasColumnName("fencing");

                    b.Property<bool?>("HandicapRamp")
                        .HasColumnType("boolean")
                        .HasColumnName("handicapramp");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<int>("LandOwning")
                        .HasColumnType("integer")
                        .HasColumnName("landowning");

                    b.Property<string>("Latitude")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("latitude");

                    b.Property<bool?>("LawnTenisCourt")
                        .HasColumnType("boolean")
                        .HasColumnName("lawnteniscourt");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("location");

                    b.Property<string>("Longitude")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("longitude");

                    b.Property<string>("MaintenanceAgency")
                        .HasColumnType("text")
                        .HasColumnName("maintenanceagency");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<int?>("OpeningYear")
                        .HasColumnType("integer")
                        .HasColumnName("openingyear");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.Property<bool?>("RunningTrack")
                        .HasColumnType("boolean")
                        .HasColumnName("runningtrack");

                    b.Property<bool?>("ShootingRange")
                        .HasColumnType("boolean")
                        .HasColumnName("shootingrange");

                    b.Property<bool?>("SwimmingPool")
                        .HasColumnType("boolean")
                        .HasColumnName("swimmingpool");

                    b.Property<bool?>("TTHall")
                        .HasColumnType("boolean")
                        .HasColumnName("tthall");

                    b.Property<bool?>("TinShed")
                        .HasColumnType("boolean")
                        .HasColumnName("tinshed");

                    b.Property<bool?>("ToiletFacility")
                        .HasColumnType("boolean")
                        .HasColumnName("toiletfacility");

                    b.Property<int?>("TotalArea")
                        .HasColumnType("integer")
                        .HasColumnName("totalarea");

                    b.Property<int?>("TotalFloors")
                        .HasColumnType("integer")
                        .HasColumnName("totalfloors");

                    b.Property<int?>("TotalTrees")
                        .HasColumnType("integer")
                        .HasColumnName("totaltrees");

                    b.Property<bool?>("VehicleParking")
                        .HasColumnType("boolean")
                        .HasColumnName("vehicleparking");

                    b.Property<bool?>("WaterHarvesting")
                        .HasColumnType("boolean")
                        .HasColumnName("waterharvesting");

                    b.Property<bool?>("WeightLiftingHall")
                        .HasColumnType("boolean")
                        .HasColumnName("weightliftinghall");

                    b.Property<bool?>("WrestlingArena")
                        .HasColumnType("boolean")
                        .HasColumnName("wrestlingarena");

                    b.Property<bool?>("park")
                        .HasColumnType("boolean")
                        .HasColumnName("park");

                    b.HasKey("BuildingId");

                    b.ToTable("tbmsinfrastructure");
                });

            modelBuilder.Entity("edumis.Models.Masters.PostsModel", b =>
                {
                    b.Property<string>("PostCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("postcode");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<bool>("IsGazetted")
                        .HasColumnType("boolean")
                        .HasColumnName("isgazetted");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("isvalid");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("orderdate");

                    b.Property<string>("OrderNo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("orderno");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("posttitle");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.HasKey("PostCode");

                    b.ToTable("tbmsposts");
                });

            modelBuilder.Entity("edumis.Models.Masters.SchoolDetailsModel", b =>
                {
                    b.Property<string>("BranchId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("branchid");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("Assembly")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("assembly");

                    b.Property<string>("Constituency")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("constituency");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<int?>("EstbYear")
                        .HasColumnType("integer")
                        .HasColumnName("estbyear");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("Hospital")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("hospital");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<int?>("Nomenclature")
                        .HasColumnType("integer")
                        .HasColumnName("nomenclature");

                    b.Property<string>("PoliceStation")
                        .HasColumnType("text")
                        .HasColumnName("policestation");

                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.Property<int?>("Shift")
                        .HasColumnType("integer")
                        .HasColumnName("shift");

                    b.PrimitiveCollection<int[]>("Streams")
                        .HasColumnType("integer[]")
                        .HasColumnName("streams");

                    b.Property<string>("UDISECode")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("udisecode");

                    b.HasKey("BranchId");

                    b.ToTable("tbms_schooldetails");
                });

            modelBuilder.Entity("edumis.Models.Masters.ZonesModel", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RowId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("districtid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.HasKey("RowId");

                    b.ToTable("tbms_zones");
                });

            modelBuilder.Entity("edumis.Models.News.NewsModel", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExternalLink")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("externallink");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<DateOnly>("NewsDate")
                        .HasColumnType("date")
                        .HasColumnName("newsdate");

                    b.Property<string>("Photo")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("photo");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("VideoLink")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("videolink");

                    b.HasKey("RowId");

                    b.ToTable("tbmsnews");
                });

            modelBuilder.Entity("edumis.Models.SMC.MeetingAgendaModel", b =>
                {
                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meetingid");

                    b.Property<int>("SerialNo")
                        .HasColumnType("integer")
                        .HasColumnName("serialno");

                    b.Property<int>("AgendaCode")
                        .HasColumnType("integer")
                        .HasColumnName("agendacode");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<string>("OtherDetails")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("otherdetails");

                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.HasKey("MeetingId", "SerialNo");

                    b.ToTable("tbsmc_meeting_agenda");
                });

            modelBuilder.Entity("edumis.Models.SMC.MeetingAttachmentsModel", b =>
                {
                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meetingid");

                    b.Property<int>("SerialNo")
                        .HasColumnType("integer")
                        .HasColumnName("serialno");

                    b.Property<string>("ContentType")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contenttype");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("Extension")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("extension");

                    b.Property<string>("FileName")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("filename");

                    b.Property<string>("FilePath")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("filepath");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.Property<string>("Title")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.HasKey("MeetingId", "SerialNo");

                    b.ToTable("tbsmc_meeting_attachments");
                });

            modelBuilder.Entity("edumis.Models.SMC.MeetingHistoryModel", b =>
                {
                    b.Property<long>("RowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowID"));

                    b.Property<int>("AmendmentNo")
                        .HasColumnType("integer")
                        .HasColumnName("amendmentno");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("fieldname");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fieldvalue");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meetingid");

                    b.HasKey("RowID");

                    b.ToTable("tbsmc_meeting_hist");
                });

            modelBuilder.Entity("edumis.Models.SMC.MeetingModel", b =>
                {
                    b.Property<Guid>("MeetingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("meetingid");

                    b.PrimitiveCollection<string[]>("Attendees")
                        .HasColumnType("varchar[]")
                        .HasColumnName("attendees");

                    b.Property<string>("BranchId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("branchid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("ForSession")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("forsession");

                    b.PrimitiveCollection<string[]>("Invitees")
                        .HasColumnType("varchar[]")
                        .HasColumnName("invitees");

                    b.Property<DateOnly>("MeetingDate")
                        .HasColumnType("date")
                        .HasColumnName("meetingdate");

                    b.Property<TimeOnly>("MeetingTime")
                        .HasColumnType("time")
                        .HasColumnName("meetingtime");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<string>("Mom_Brief")
                        .HasColumnType("text")
                        .HasColumnName("mom_brief");

                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.HasKey("MeetingId");

                    b.HasIndex("BranchId");

                    b.HasIndex("ForSession");

                    b.ToTable("tbsmc_meeting");
                });

            modelBuilder.Entity("edumis.Models.SMC.MeetingResolutionsModel", b =>
                {
                    b.Property<Guid>("ResolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("resolutionid");

                    b.Property<decimal?>("ActualCost")
                        .HasColumnType("numeric")
                        .HasColumnName("actualcost");

                    b.PrimitiveCollection<int[]>("AgendaSrNo")
                        .HasColumnType("integer[]")
                        .HasColumnName("agenda_srno");

                    b.Property<DateOnly?>("ClosingDate")
                        .HasColumnType("date")
                        .HasColumnName("closingdate");

                    b.Property<string>("Comments")
                        .HasColumnType("Text")
                        .HasColumnName("comments");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("numeric")
                        .HasColumnName("estimatedcost");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("isclosed");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meetingid");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("Text")
                        .HasColumnName("resolution");

                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.HasKey("ResolutionId");

                    b.HasIndex("MeetingId");

                    b.ToTable("tbsmc_meeting_resolutions");
                });

            modelBuilder.Entity("edumis.Models.SMC.MemberDeviceTokensModel", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("memberid");

                    b.Property<int>("SerialNo")
                        .HasColumnType("integer")
                        .HasColumnName("serialno");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("devicename");

                    b.Property<string>("MacAddress")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("macaddress");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("MemberId", "SerialNo");

                    b.ToTable("tbsmc_devicetokens");
                });

            modelBuilder.Entity("edumis.Models.SMC.MemberRegistrationsModel", b =>
                {
                    b.Property<string>("ForSession")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("forsession");

                    b.Property<string>("BranchId")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("branchid");

                    b.Property<string>("UniqueId")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("uniqueid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<int>("DesignationId")
                        .HasColumnType("integer")
                        .HasColumnName("designationid");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("memberid");

                    b.Property<int>("MemberType")
                        .HasColumnType("integer")
                        .HasColumnName("membertype");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("mobileno");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("name");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea")
                        .HasColumnName("photo");

                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.HasKey("ForSession", "BranchId", "UniqueId");

                    b.HasIndex("BranchId");

                    b.ToTable("tbsmc_registeredmembers");
                });

            modelBuilder.Entity("edumis.Models.SMC.SMCAccountsModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<string>("BranchId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("branchid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("EmailId")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("emailid");

                    b.Property<bool?>("IsAccountLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("isaccountlocked");

                    b.Property<bool?>("IsLoggedIn")
                        .HasColumnType("boolean")
                        .HasColumnName("isloggedin");

                    b.Property<bool?>("IsPwdChangeWarningSent")
                        .HasColumnType("boolean")
                        .HasColumnName("ispwdchangewarningsent");

                    b.Property<bool?>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("isvalid");

                    b.Property<DateTime?>("LastPwdChangedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastpwdchangeddate");

                    b.Property<int?>("MaxNoOfInvalidLoginAttempt")
                        .HasColumnType("integer")
                        .HasColumnName("maxnoofinvalidloginattempt");

                    b.Property<string>("MobileNo")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("mobileno");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("password");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea")
                        .HasColumnName("photo");

                    b.Property<string>("PrevPassword1")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("prevpassword1");

                    b.Property<string>("PrevPassword2")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("prevpassword2");

                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.Property<int>("UserType")
                        .HasColumnType("integer")
                        .HasColumnName("usertype");

                    b.HasKey("UserId");

                    b.ToTable("tbsmc_logins");
                });

            modelBuilder.Entity("edumis.Models.SMC.SMCFundTransactionsModel", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("transactionid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meetingid");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<string>("ReferenceDocNo")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("refdocno");

                    b.Property<Guid>("ResolutionId")
                        .HasColumnType("uuid[]")
                        .HasColumnName("resolutionid");

                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transdate");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer")
                        .HasColumnName("transtype");

                    b.HasKey("TransactionId");

                    b.HasIndex("MeetingId");

                    b.ToTable("tbsmc_transactions");
                });

            modelBuilder.Entity("edumis.Models.SMC.SMCTransactionAttachmentsModel", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transactionid");

                    b.Property<int>("SerialNo")
                        .HasColumnType("integer")
                        .HasColumnName("serialno");

                    b.Property<string>("ContentType")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contenttype");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("Extension")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("extension");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("filename");

                    b.Property<string>("FilePath")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("filepath");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.Property<Guid?>("SMCFundTransactionsModelTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.HasKey("TransactionId", "SerialNo");

                    b.HasIndex("SMCFundTransactionsModelTransactionId");

                    b.ToTable("tbsmc_trans_attachments");
                });

            modelBuilder.Entity("edumis.Models.Tenders.TendersModel", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expirydate");

                    b.Property<string>("FileLink")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("filelink");

                    b.Property<string>("FinancialYear")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("financialyear");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("isvalid");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<DateTime>("TenderDate")
                        .HasColumnType("date")
                        .HasColumnName("tenderdate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("RowId");

                    b.ToTable("tbweb_tenders");
                });

            modelBuilder.Entity("edumis.Models.Users.UserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createddate");

                    b.Property<bool?>("IsAccountLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("isaccountlocked");

                    b.Property<bool?>("IsLoggedIn")
                        .HasColumnType("boolean")
                        .HasColumnName("isloggedin");

                    b.Property<bool?>("IsPwdChangeWarningSent")
                        .HasColumnType("boolean")
                        .HasColumnName("ispwdchangewarningsent");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("isvalid");

                    b.Property<DateTime?>("LastPwdChangedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastpwdchangeddate");

                    b.Property<int?>("MaxNoOfInvalidLoginAttempt")
                        .HasColumnType("integer")
                        .HasColumnName("maxnoofinvalidloginattempt");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifieddate");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("password");

                    b.Property<string>("Photo")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("photo");

                    b.Property<string>("PrevPassword1")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("prevpassword1");

                    b.Property<string>("PrevPassword2")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("prevpassword2");

                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rowid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("uniqueid");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer")
                        .HasColumnName("userrole");

                    b.Property<int>("UserType")
                        .HasColumnType("integer")
                        .HasColumnName("usertype");

                    b.HasKey("UserId");

                    b.ToTable("tbmslogin");
                });

            modelBuilder.Entity("edumis.Models.Global.CodeValuesModel", b =>
                {
                    b.HasOne("edumis.Models.Global.CodesModel", "CodesNavigation")
                        .WithMany()
                        .HasForeignKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodesNavigation");
                });

            modelBuilder.Entity("edumis.Models.SMC.MeetingAgendaModel", b =>
                {
                    b.HasOne("edumis.Models.SMC.MeetingModel", "MeetingNavigation")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingNavigation");
                });

            modelBuilder.Entity("edumis.Models.SMC.MeetingAttachmentsModel", b =>
                {
                    b.HasOne("edumis.Models.SMC.MeetingModel", "MeetingNavigation")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingNavigation");
                });

            modelBuilder.Entity("edumis.Models.SMC.MeetingModel", b =>
                {
                    b.HasOne("edumis.Models.Masters.BranchesModel", "BranchesNavigation")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edumis.Models.Global.SessionInfoModel", "SessionNavigation")
                        .WithMany()
                        .HasForeignKey("ForSession")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchesNavigation");

                    b.Navigation("SessionNavigation");
                });

            modelBuilder.Entity("edumis.Models.SMC.MeetingResolutionsModel", b =>
                {
                    b.HasOne("edumis.Models.SMC.MeetingModel", "MeetingNavigation")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingNavigation");
                });

            modelBuilder.Entity("edumis.Models.SMC.MemberRegistrationsModel", b =>
                {
                    b.HasOne("edumis.Models.Masters.BranchesModel", "BranchesNavigation")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edumis.Models.Global.SessionInfoModel", "SessionNavigation")
                        .WithMany()
                        .HasForeignKey("ForSession")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchesNavigation");

                    b.Navigation("SessionNavigation");
                });

            modelBuilder.Entity("edumis.Models.SMC.SMCFundTransactionsModel", b =>
                {
                    b.HasOne("edumis.Models.SMC.MeetingModel", "MeetingNavigation")
                        .WithMany()
                        .HasForeignKey("MeetingId");

                    b.Navigation("MeetingNavigation");
                });

            modelBuilder.Entity("edumis.Models.SMC.SMCTransactionAttachmentsModel", b =>
                {
                    b.HasOne("edumis.Models.SMC.SMCFundTransactionsModel", null)
                        .WithMany("SMCTransactionAttachmentsList")
                        .HasForeignKey("SMCFundTransactionsModelTransactionId");

                    b.HasOne("edumis.Models.SMC.SMCFundTransactionsModel", "SMCFundTransactionNavigation")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SMCFundTransactionNavigation");
                });

            modelBuilder.Entity("edumis.Models.SMC.SMCFundTransactionsModel", b =>
                {
                    b.Navigation("SMCTransactionAttachmentsList");
                });
#pragma warning restore 612, 618
        }
    }
}
