using System.ComponentModel.DataAnnotations;

namespace edumis.Models.Masters.DTO;

public record InfrastructureDTO(
    [MaxLength(50)] string BuildingId,
    [MaxLength(500)] string? BuildingName,
    [MaxLength(500)] string? Location,
    [MaxLength(50)] string? Longitude,
    [MaxLength(50)] string? Latitude,
    [Required] int LandOwning,
    int? TotalFloors,
    int? TotalArea,
    bool? Fencing,
    bool? TinShed,
    bool? park,
    int? TotalTrees,
    bool? WaterHarvesting,
    bool? DrinkingWater,
    bool? ToiletFacility,
    bool? HandicapRamp,
    bool? CycleStand,
    bool? VehicleParking,
    bool? Accommodation,
    bool? BadmintonCourt,
    bool? TTHall,
    bool? BasketBallCourt,
    bool? ShootingRange,
    bool? SwimmingPool,
    bool? BoxingArena,
    bool? WrestlingArena,
    bool? RunningTrack,
    bool? WeightLiftingHall,
    bool? LawnTenisCourt,
    bool? ArcheryGround,
    int? OpeningYear,
    string? MaintenanceAgency,
    bool IsActive,
    [Required][MaxLength(100)] string LoggedInUserId
);

public record InfrastructureDetailsDTO(
    string BuildingId,
    string? BuildingName,
    string? Location,
    string? Longitude,
    string? Latitude,
    int LandOwning,
    string LandOwningTitle,
    int? TotalFloors,
    int? TotalArea,
    bool? Fencing,
    bool? TinShed,
    bool? park,
    int? TotalTrees,
    bool? WaterHarvesting,
    bool? DrinkingWater,
    bool? ToiletFacility,
    bool? HandicapRamp,
    bool? CycleStand,
    bool? VehicleParking,
    bool? Accommodation,
    bool? BadmintonCourt,
    bool? TTHall,
    bool? BasketBallCourt,
    bool? ShootingRange,
    bool? SwimmingPool,
    bool? BoxingArena,
    bool? WrestlingArena,
    bool? RunningTrack,
    bool? WeightLiftingHall,
    bool? LawnTenisCourt,
    bool? ArcheryGround,
    int? OpeningYear,
    string? MaintenanceAgency,
    bool IsActive
);
